# Generated by Django 5.2.15 on 2026-07-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
